- hosts: all
  become: true
  vars:                                                               # Add
    path_to_nginx_conf: "./nginx.conf"                                # These
    nginx_message: "Hello from Ansible on {{ inventory_hostname }}"   # Lines
  tasks:
  - name: Install NGINX
    apt:
      name: nginx
      state: latest
      update_cache: true
  - name: Start NGINX Service
    service:
      name: nginx
      state: started
  - name: Add nginx conf
    template:
      src: "{{ path_to_nginx_conf }}"
      dest: /etc/nginx/nginx.conf
    notify: Restart nginx
  - name: Git clone
    ansible.builtin.git:
      repo: 'https://github.com/Zake-Ahmed/123.git'
      dest: ./123
  - name: Touch file
    ansible.builtin.file:
      path: ./123/ansible.txt
      state: touch
      #code: echo {{ inventory_hostname }} > ./123/ansible.txt
  - name: write ip address to file
    shell: echo {{ inventory_hostname }} > ./123/ansible.txt
  - name: print if OS is ubuntu
    debug: 
      msg: Hi the OS is ubuntu
    when: ansible_lsb.id == "Ubuntu"

  
  
  handlers:
  - name: Restart nginx
    service: 
      name: nginx
      state: restarted